name: 'Build, Lint, Test'

on: [pull_request]

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm install
      - run: yarn lint
      - run: yarn prettier
      - run: yarn test:precommit 